### ISSUE TITLE
git failing with exit code 128

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-skills-kit#56]
**Describe the bug**
Attempted to upgrade the Home Assistant Skill. MSK returned the following:
```
Upgrading an existing skill in the skill repo...

Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 264 bytes | 264.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/krisgesling/mycroft-skills
 + e5423f6...2403955 upgrade-homeassistant -> upgrade-homeassistant (forced update)
Branch 'upgrade-homeassistant' set up to track remote branch 'upgrade-homeassistant' from 'fork'.
Traceback (most recent call last):
  File "/home/mycroft/mycroft-core/.venv/bin/msk", line 8, in <module>
    sys.exit(main())
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/msk/__main__.py", line 64, in main
    return action_to_cls[args.action](args).perform()
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/msk/actions/submit.py", line 38, in perform
    self.action.perform()
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/msk/actions/upgrade.py", line 76, in perform
    title, body = self.create_pr_message(self.skill.git, self.skill.hub)
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/msk/actions/upgrade.py", line 60, in create_pr_message
    commits='\n'.join(
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/msk/actions/upgrade.py", line 62, in <genexpr>
    skill_git.show('-s', sha, format='%s'),
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/mycroft/mycroft-core/.venv/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git show --format=%s -s 
  stderr: 'fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''
```

**Environment (please complete the following information):**
Tried on both a Debian desktop, and Pi running Ubuntu 20.04

**Additional context**
I haven't yet dug into this at all.

**Comment by krisgesling** [comment]
The SkillEntry from MSM is returning an empty string for the current sha which causes the revision list lookup to return an empty list.

We should handle this just in case but the real fix is probably in MSM.
