### ISSUE TITLE
skills repo clone/update fails on desktop install

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-skills-kit#8]
i develop on a git install, i even use a a different skills folder in my setup, i can not use msk

msk should support skills in any path

i manually created the opt/mycroft folder

getting all sorts of permissions issues when cloning skills repo

tried to use the terminal to manually clone it the first time, but repo update still fails when running msk

```

Traceback (most recent call last):
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msm/exceptions.py", line 104, in git_to_msm_exceptions
    yield
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msm/skill_repo.py", line 57, in update
    git.config('remote.origin.url', self.url)
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msm/util.py", line 33, in wrapper
    return super(Git, self).__getattr__(item)(*args, env=env, **kwargs)
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git config remote.origin.url https://github.com/MycroftAI/mycroft-skills
  stderr: 'fatal: not in a git directory'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/core/.venv/bin/msk", line 11, in <module>
    sys.exit(main())
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msk/__main__.py", line 67, in main
    return console_actions[args.action](args).perform()
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msk/actions/upload.py", line 115, in perform
    branch = SkillData(self.entry).add_to_repo()
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msk/repo_action.py", line 98, in add_to_repo
    self.repo.msminfo.update()
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msm/skill_repo.py", line 58, in update
    git.fetch()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/PycharmProjects/core/.venv/lib/python3.5/site-packages/msm/exceptions.py", line 106, in git_to_msm_exceptions
    raise GitException('Git command failed: {}'.format(repr(e))) from e
msm.exceptions.GitException: Git command failed: GitCommandError(['git', 'config', 'remote.origin.url', 'https://github.com/MycroftAI/mycroft-skills'], 128, b'fatal: not in a git directory', b'')


```

**Comment by JarbasAl** [comment]
nvm, noticed there is an arg for this!

**Comment by JarbasAl** [comment]
reopening and renaming, getting all sorts of permissions issues when cloning skills repo

tried to use the terminal to manually clone it the first time, but rep update fails
